// HEAP IS A BINARY TREE WHICH IS A COMPLETE BINARY TREE
// COMLETE BINARY TREE MEANS ALL LEVEL ARE FILLED COMPLETELY EXCEPT MAY BE LAST LEVEL UNFILLED 
// BUT LAST LEVEL HAS KEYS AS LEFT AS POSSIBLE MEANS THERE SHOULDNOT BE ANY NODE EMPTY WHICH CAN GO TO LEFT CHILD
// EX.           (1)
//               /  \ 
//             (2)   (3)
//             / \     \ 
//          (4)   (5)   (6)
//          NOT A COMPLETE TREE ( AS 6 CAN GO TO LEFT OF 3 )

// MIN HEAP => PARENT NODE HAS SMALLER VALUE THAN CHILD NODE ( <= )
// MAX HEAP => PARENT NODE HAS LARGER VALUE THAN CHILD NODE ( >= )

// REPERESENTATION OF A HEAP USING AN ARRAY
// >>> ROOT NODE WILL BE AT INDEX 1
// >>> FOR NODE AT INDEX I, LEFT CHILD WILL BE AT 2*I AND RIGHT CHILD WILL BE AT 2*I +1
// >>> FOR NODE AT INDEX I, IT'S PARENT NODE WILL BE AT I/2

//    COMPLETE BINARY TREE      ARRAY REPERSENTATION
//       (A)
//      /    \    
//     (B)   (C)              => [A B C D E F]
//     /  \   /                   1 2 3 4 5 6  (INDEX)
//  (D)  (E)  (F)


// FOR 0 BASED INDEXING => LEFT CHILD - 2*I + 1 AND RIGHT CHILD - 2*I + 2
//                      => PARENT AT (I - 1) / 2