// PASS BY REFERENCE 
// IF WE WANT TO MAKE SOME CHANGES IN THE FORMAL VARIABLES WHICH CAN BE ANY DATASTRUCTURES ALSO SO WE HAVE TO USE AMPERSANT OPERATOR
// OTHERWISE NO CHANGE WILL OCCUR ON THAT

#include<iostream>
using namespace std;
void changeValue(int &z){                // HERE AMPERSENT OPERATOR IS USED SO HERE BOTH WILL ASSIGN SAME PLACE
    z=100;
}
int main(){
    int a=5;
    changeValue(a);                      // SO HERE VALUE OF A AND Z BOTH WILL BE 100
    cout<<a;                             // PRINT OF 100 WILL OCCUR
    return 0;
}
// SO USING AMPERSANT ON THE FORMAL PARAMETERS WE CAN HAVE SAME LOCATION/ADDRESS FOR BOTH FORMAL AND INFORMAL PARAMETERS