// CONVERSION OF INFIX TO PREFIX

// FIRST REVERSE THE WHOLE STRING AND THEN TRAVERSE ONCE TO CONVERT OPENING BRACKET TO CLOSING AND VICE VERSA
// THEN ALL THE THING WHICH WE HAVE DONE FOR POSTFIX CAN BE APPLIED HERE

#include<bits/stdc++.h>
using namespace std;

int main(){

    return 0;
}