// CONVERSION OF INFIX TO POSTFIX

// MOVE FROM LEFT TO RIGHT
// IF IT IS AN OPERAND THEN PRINT
// IF IT IS AN OPENING BRACKET INSERT IN STACK
// IF IT IS AN CLOSING BRACKET POP OUT TILL WE GET OPENING BRACKET
// IF OPERATOR THEN POP FROM STACK AND PRINT UNTIL AN OPERATOR WITH LESS PRECEDENCE IS FOUND

#include<bits/stdc++.h>
using namespace std;

int main(){

    return 0;
}